### ISSUE TITLE
[PE-D][Tester B] Inconsistency in UG command inputs

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-F14-1/tp#113]
Expected: Commands should use similar notations if referring to the same input e.g. index
Actual: Commands are using different notations

Parameter1 :

![image.png](https://raw.githubusercontent.com/jing-xiang/ped/main/files/0b53aaa4-a8cd-4e0b-8b17-d79389a59d2d.png)

Parameter2:

![image.png](https://raw.githubusercontent.com/jing-xiang/ped/main/files/459651ed-e3d6-422c-93d6-6b24dcd17439.png)

Delete function does not use /i to validate the index parsing

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: jing-xiang/ped#2

**Comment by STeng618** [comment]
Modify delete and list
