### ISSUE TITLE
[PE-D][Tester A] Future Dates For Past Expenses Allowed

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-F14-1/tp#122]
![Screenshot 2024-04-05 at 17.17.31.png](https://raw.githubusercontent.com/j013n3/ped/main/files/a4272b5e-b697-49b7-81b9-9ed7df8535b0.png)

may be good to disallow future dates 

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: j013n3/ped#2

**Comment by yeozhishen** [comment]
similar bug to #129
