### ISSUE TITLE
[PE-D][Tester A] Amount for large integers not reflected 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-F14-1/tp#132]
![Screenshot 2024-04-05 at 18.25.41.png](https://raw.githubusercontent.com/j013n3/ped/main/files/2f2d90b1-b490-4878-a8a5-c1ee031e4bb2.png)

When large integers are entered, the amount is not accurately reflected.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: j013n3/ped#5

**Comment by yeozhishen** [comment]
limted amount specified to 7 integers
