### ISSUE TITLE
[PE-D][Tester A] Incorrect Handling of non-existent date

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-F14-1/tp#135]
![Screenshot 2024-04-05 at 22.01.47.png](https://raw.githubusercontent.com/j013n3/ped/main/files/581d626a-1c33-473b-abba-57638a99bafb.png)

Can improve data handling by signalling to user that 30 february does not exist instead of printing date out as 29 february. 

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: j013n3/ped#8

**Comment by yeozhishen** [comment]
similar issue as #116
