### ISSUE TITLE
Code Review for yeozhishen

### ISSUE THREAD

**Issue by Jonoans** [AY2324S2-CS2113-F14-1/tp#89]
- [x] Following coding standard for boolean naming
  - `startAppending` in [AddParser](https://github.com/AY2324S2-CS2113-F14-1/tp/blob/a7371c407fc943bcdfa01305218f353d9a761b0e/src/main/java/brokeculator/parser/AddParser.java) could be renamed to `shouldStartAppending` / `shouldAppend`
  - Same for boolean variables in [CategoryParser](https://github.com/AY2324S2-CS2113-F14-1/tp/blob/6d0114a1443732eda5a32d883fe435b5f1e3d3ae/src/main/java/brokeculator/parser/CategoryParser.java)
- [x] Avoid magic strings
  - In [CategoryParser](https://github.com/AY2324S2-CS2113-F14-1/tp/blob/6d0114a1443732eda5a32d883fe435b5f1e3d3ae/src/main/java/brokeculator/parser/CategoryParser.java), the `String.equals` conditional could use the constant values `ADD_SUBCOMMAND` for example rather than `String.equals("add")`
- [x] Remove irrelevant comments
  - Line 19 of [ListParser](https://github.com/AY2324S2-CS2113-F14-1/tp/blob/a9eb0e934100be5ad652d9ebe4d114850e115dc1/src/main/java/brokeculator/parser/ListParser.java).
  
The above feedback can be applied generally to other sections of the code. The examples given are just to flag concrete examples and provide contextualised feedback.

**Comment by yeozhishen** [comment]
done
